#!/usr/bin/env python3
"""Convert XiaoTai's canonical phone shortcut PNG to a BK RGB565 asset."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

from PIL import Image


ICON_SIZE = 44


def rgb565(red: int, green: int, blue: int) -> int:
    return ((red * 31 + 127) // 255 << 11) | \
           ((green * 63 + 127) // 255 << 5) | \
           ((blue * 31 + 127) // 255)


def lines(values: list[int], formatter, count: int) -> str:
    return ",\n".join(
        "    " + ", ".join(formatter(value)
                            for value in values[offset:offset + count])
        for offset in range(0, len(values), count)
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args()

    source = args.input.read_bytes()
    image = Image.open(args.input).convert("RGBA")
    resampling = getattr(Image, "Resampling", Image)
    image = image.resize((ICON_SIZE, ICON_SIZE), resampling.LANCZOS)
    pixels = list(image.getdata())
    colors = [rgb565(red, green, blue) for red, green, blue, _ in pixels]
    alpha = [opacity for _, _, _, opacity in pixels]
    digest = hashlib.sha256(source).hexdigest()

    args.output_dir.mkdir(parents=True, exist_ok=True)
    header = f"""#ifndef XIAOTAI_PHONE_SHORTCUT_H
#define XIAOTAI_PHONE_SHORTCUT_H

#include <stdint.h>

#define XIAOTAI_PHONE_SHORTCUT_WIDTH {ICON_SIZE}U
#define XIAOTAI_PHONE_SHORTCUT_HEIGHT {ICON_SIZE}U

extern const uint16_t xiaotai_phone_shortcut_rgb565[];
extern const uint8_t xiaotai_phone_shortcut_alpha[];

#endif
"""
    generated = f"""/* Generated by tools/generate_phone_shortcut.py.
 * Source: XiaoTai starter_product/assets/phone_shortcut.png
 * Source SHA-256: {digest}
 */
#include "xiaotai_phone_shortcut.h"

const uint16_t xiaotai_phone_shortcut_rgb565[] = {{
{lines(colors, lambda value: f"0x{value:04x}", 10)}
}};

const uint8_t xiaotai_phone_shortcut_alpha[] = {{
{lines(alpha, lambda value: f"0x{value:02x}", 16)}
}};
"""
    (args.output_dir / "xiaotai_phone_shortcut.h").write_text(header)
    (args.output_dir / "xiaotai_phone_shortcut.c").write_text(generated)


if __name__ == "__main__":
    main()
