#!/usr/bin/env python3
"""Generate compact, reproducible XiaoTai UI assets.

The firmware stores the fixed WeChat mini-program code as a 1-bit module map
and a basic-CJK Unicode bitmap font. Pillow is a host-side generation
dependency; it is not required to build the firmware.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


PRODUCT_GLYPHS = (
    "小钛智能设备微信扫码添加联系人未授权正在聆听思考回复中来电接通话"
    "配置网络绑定验证码语音获取失败请稍后重试短按对话双击呼叫启动初始化"
    "连接云端成功准备就绪结束释放音频未找到多个同名远程查看画面共享中"
    "等待接听正在接通对方拒绝无人接听挂断异常恢复功能菜单聊天通讯录"
    "多人对讲表情包设置状态在线离线语音应用当前上一个下一个音量扬声器"
    "麦克风息屏分钟从不房间退出结束按住说话松开发送成员加入等待没有分配信号强度上一页下一页显示前"
    "地址需要手机完成配网热点访问选择家庭密码绑定授权后开始返回验证码"
    "轻触一下和聊聊左右滑动切换表盘你"
)
QR_MODULES = 37
QR_IMAGE_LOW = 28
QR_IMAGE_HIGH = 373


def packed_qr(path: Path) -> bytes:
    image = Image.open(path).convert("L")
    if image.size != (400, 400):
        raise SystemExit(f"expected the supplied 400x400 mini-program code, got {image.size}")
    bits: list[bool] = []
    for row in range(QR_MODULES):
        for column in range(QR_MODULES):
            x0 = round(QR_IMAGE_LOW + column * (QR_IMAGE_HIGH - QR_IMAGE_LOW) / QR_MODULES)
            x1 = round(QR_IMAGE_LOW + (column + 1) * (QR_IMAGE_HIGH - QR_IMAGE_LOW) / QR_MODULES)
            y0 = round(QR_IMAGE_LOW + row * (QR_IMAGE_HIGH - QR_IMAGE_LOW) / QR_MODULES)
            y1 = round(QR_IMAGE_LOW + (row + 1) * (QR_IMAGE_HIGH - QR_IMAGE_LOW) / QR_MODULES)
            cell = image.crop((x0, y0, x1, y1))
            bits.append(sum(cell.getdata()) < 128 * cell.width * cell.height)
    output = bytearray((len(bits) + 7) // 8)
    for index, black in enumerate(bits):
        if black:
            output[index // 8] |= 0x80 >> (index % 8)
    return bytes(output)


def glyph_rows(font: ImageFont.FreeTypeFont, character: str) -> bytes:
    image = Image.new("1", (16, 16), 0)
    draw = ImageDraw.Draw(image)
    left, top, right, bottom = draw.textbbox((0, 0), character, font=font)
    width, height = right - left, bottom - top
    if ord(character) < 0x80:
        # Latin captions need denser cells than ideographs. Keep ASCII inside
        # the left 8 pixels so the device renderer can advance by 9 pixels.
        draw.text(((8 - width) // 2 - left, (16 - height) // 2 - top),
                  character, font=font, fill=1)
    else:
        draw.text(((16 - width) // 2 - left, (16 - height) // 2 - top),
                  character, font=font, fill=1)
    output = bytearray()
    for y in range(16):
        value = 0
        for x in range(16):
            if image.getpixel((x, y)):
                value |= 1 << (15 - x)
        output.extend((value >> 8, value & 0xFF))
    return bytes(output)


def basic_cjk_characters() -> str:
    """Match the ESP32 product font's UTF-8 coverage at 1 bit per pixel."""
    characters = set(PRODUCT_GLYPHS)
    characters.update("°℃")  # angles and AI temperature captions
    ranges = (
        (0x20, 0x7E),       # ASCII
        (0x2000, 0x206F),   # general punctuation
        (0x2190, 0x22FF),   # arrows and mathematical operators
        (0x2500, 0x25FF),   # box drawing and geometric shapes
        (0x3000, 0x303F),   # CJK punctuation
        (0x4E00, 0x9FFF),   # CJK unified ideographs (basic block)
        (0xFF00, 0xFFEF),   # full-width forms
    )
    for first, last in ranges:
        characters.update(chr(codepoint)
                          for codepoint in range(first, last + 1))
    return "".join(sorted(characters, key=ord))


def byte_lines(data: bytes, indent: str = "    ") -> str:
    chunks = []
    for offset in range(0, len(data), 12):
        chunks.append(indent + ", ".join(f"0x{value:02x}" for value in data[offset:offset + 12]))
    return ",\n".join(chunks)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--qr", type=Path, required=True)
    parser.add_argument("--font", type=Path,
                        default=Path("/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc"))
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args()

    qr = packed_qr(args.qr)
    font = ImageFont.truetype(str(args.font), 16, index=2)
    glyphs = [(ord(character), glyph_rows(font, character))
              for character in basic_cjk_characters()]

    args.output_dir.mkdir(parents=True, exist_ok=True)
    header = """#ifndef XIAOTAI_UI_ASSETS_H
#define XIAOTAI_UI_ASSETS_H

#include <stddef.h>
#include <stdint.h>

#define XIAOTAI_WX_QR_MODULES 37U

typedef struct {
    uint32_t codepoint;
    uint8_t bitmap[32];
} xiaotai_cjk_glyph_t;

extern const uint8_t xiaotai_wx_qr_bits[];
extern const xiaotai_cjk_glyph_t xiaotai_cjk_glyphs[];
extern const size_t xiaotai_cjk_glyph_count;

#endif
"""
    source = """/* Generated by tools/generate_ui_assets.py. */
#include "xiaotai_ui_assets.h"

const uint8_t xiaotai_wx_qr_bits[] = {
%s
};

const xiaotai_cjk_glyph_t xiaotai_cjk_glyphs[] = {
%s
};

const size_t xiaotai_cjk_glyph_count =
    sizeof(xiaotai_cjk_glyphs) / sizeof(xiaotai_cjk_glyphs[0]);
""" % (
        byte_lines(qr),
        ",\n".join(
            "    {0x%04xU, {\n%s\n    }}" % (codepoint, byte_lines(bitmap, "        "))
            for codepoint, bitmap in glyphs
        ),
    )
    (args.output_dir / "xiaotai_ui_assets.h").write_text(header)
    (args.output_dir / "xiaotai_ui_assets.c").write_text(source)


if __name__ == "__main__":
    main()
