#ifndef XIAOTAI_INTENT_H
#define XIAOTAI_INTENT_H

typedef enum {
    XIAOTAI_INTENT_NONE = 0,
    XIAOTAI_INTENT_PRIMARY,
    XIAOTAI_INTENT_QUICK_CALL,
    XIAOTAI_INTENT_HOME_WECHAT_CALL,
    XIAOTAI_INTENT_PTT_PRESS,
    XIAOTAI_INTENT_PTT_RELEASE,
    XIAOTAI_INTENT_PTT_HOLD,
} xiaotai_intent_t;

#endif
