/* Generated by tools/generate_binding_digits.py. */
#ifndef BINDING_DIGITS_H
#define BINDING_DIGITS_H
#include <stddef.h>
#include <stdint.h>
typedef struct { size_t offset; size_t length; } binding_digit_clip_t;
static const binding_digit_clip_t binding_digit_clips[10] = {
    {0U, 34860U},
    {34860U, 23052U},
    {57912U, 22428U},
    {80340U, 29440U},
    {109780U, 24808U},
    {134588U, 26336U},
    {160924U, 24020U},
    {184944U, 25824U},
    {210768U, 19664U},
    {230432U, 26436U},
};
static const binding_digit_clip_t binding_prompt_clip = {256868U, 129580U};
#endif
