#!/usr/bin/env python3
"""Generate the bundled 16 kHz stereo PCM Mandarin digit prompts.

This is an offline authoring step. Firmware builds use the committed PCM asset.
"""

from __future__ import annotations

import pathlib
import subprocess
import tempfile


ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "components/starter_media/assets"
DIGITS = "零一二三四五六七八九"
PROMPT = "绑定验证码"


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    offsets: list[tuple[int, int]] = []
    audio = bytearray()
    with tempfile.TemporaryDirectory() as temporary:
        scratch = pathlib.Path(temporary)
        for index, digit in enumerate([*DIGITS, PROMPT]):
            wave = scratch / f"{index}.wav"
            pcm = scratch / f"{index}.pcm"
            subprocess.run(
                ["espeak-ng", "-v", "zh", "-s", "125", "-w", str(wave), digit],
                check=True,
            )
            subprocess.run(
                [
                    "ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
                    "-i", str(wave), "-af",
                    "silenceremove=start_periods=1:start_threshold=-45dB:"
                    "stop_periods=-1:stop_threshold=-45dB",
                    "-ar", "16000", "-ac", "2", "-f", "s16le", str(pcm),
                ],
                check=True,
            )
            data = pcm.read_bytes()
            if len(data) < 3200 or len(data) % 4:
                raise ValueError(f"digit {index} has invalid PCM length {len(data)}")
            offsets.append((len(audio), len(data)))
            audio.extend(data)
    (OUT / "binding_digits.pcm").write_bytes(audio)
    lines = [
        "/* Generated by tools/generate_binding_digits.py. */",
        "#ifndef BINDING_DIGITS_H",
        "#define BINDING_DIGITS_H",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "typedef struct { size_t offset; size_t length; } binding_digit_clip_t;",
        "static const binding_digit_clip_t binding_digit_clips[10] = {",
    ]
    lines.extend(f"    {{{start}U, {length}U}}," for start, length in offsets[:10])
    lines.extend(["};", f"static const binding_digit_clip_t binding_prompt_clip = {{{offsets[10][0]}U, {offsets[10][1]}U}};", "#endif", ""])
    (OUT / "binding_digits.h").write_text("\n".join(lines))
    print(f"generated {len(audio)} PCM bytes")


if __name__ == "__main__":
    main()
