#pragma once

#define AI_BUTTON GPIO_7
#define AMPLIFIER_POWER_GPIO GPIO_8
#define AMPLIFIER_PLAY_GPIO GPIO_23

#define CAMERA_PWDN_GPIO GPIO_40
#define CAMERA_RESET_GPIO GPIO_41
#define CAMERA_SCCB_SCL_GPIO GPIO_42
#define CAMERA_SCCB_SDA_GPIO GPIO_43

#define LCD_MASTER_POWER GPIO_22
#define LCD_POWER GPIO_13
#define LCD_BACKLIGHT GPIO_25
#define XIAOTAI_LCD_SPI_ID 1
#define XIAOTAI_LCD_DC_GPIO GPIO_5
#define XIAOTAI_LCD_RESET_GPIO GPIO_12

#define TOUCH_NATIVE_WIDTH 240
#define TOUCH_NATIVE_HEIGHT 320
